name: Integration tests
run-name: ${{ github.actor }}
on: [push]
jobs:
  Run-Integration-Tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x, 16.x]

    steps:
      env:
        EBAY_CLIENT_ID: ${{ secrets.EBAY_CLIENT_ID }}
        EBAY_CLIENT_SECRET: ${{ secrets.EBAY_CLIENT_SECRET }}
        EBAY_REDIRECT_URI: ${{ secrets.EBAY_REDIRECT_URI }}

      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run integration-test
      